### PR TITLE
Add JSON download index

### PR DESCRIPTION
**Pull request by michael-schnell**
The [event-store-maven-plugin](https://github.com/fuinorg/event-store-maven-plugin) downloads the latest version of the event store if not nailed to a specific version. Currently it's not easy to determine the latest event store version programmatically. It would be nice to have a JSON file that contains the download information. This would allow downloading the event store just knowing the OS ("windows", "linux" or "mac") and the version without hard coding the download URLs.

### CODE REVIEW

**Comment by jen20** [comment]
:+1: on this as a feature, but it needs to go on `geteventstore.com` - this is no longer used as far as I'm aware. @danleech is that the case?

**Comment by danleech** [comment]
I’ve added a [downloads.json](https://github.com/EventStore/geteventstore.com/blob/gh-pages/_data/downloads.json) file to the website repo. When the site is generated by Jekyll a copy of this will be made to [https://geteventstore.com/downloads/downloads.json](https://geteventstore.com/downloads/downloads.json). The JSON has a little more structure than your PR; I hope that’s okay. I’ll push this update to the web server later today (when I can find the FTP credentials... @jen20 have you change the MT password recently?).

**Comment by michael-schnell** [comment]
Great. Format looks good.

**Comment by danleech** [comment]
Okay, JSON file is live at https://geteventstore.com/downloads/downloads.json

**Pull request closed without merging**
